# Generated by Django 4.1.7 on 2023-04-07 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('coursename', models.CharField(max_length=50)),
                ('enrolllist', models.TextField()),
                ('coursedescription', models.TextField()),
                ('gradedistribution', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('createtime', models.DateTimeField()),
                ('keyword', models.TextField()),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('multimedia', models.TextField()),
                ('reply', models.TextField()),
                ('likes', models.TextField()),
                ('editted', models.BooleanField()),
                ('flagged', models.TextField()),
                ('privacy', models.TextField()),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hydra_learning_management_system.courses')),
            ],
        ),
        migrations.CreateModel(
            name='Quizzes',
            fields=[
                ('qid', models.AutoField(primary_key=True, serialize=False)),
                ('ddl', models.DateTimeField()),
                ('q1', models.TextField()),
                ('q2', models.TextField()),
                ('q3', models.TextField()),
                ('ans', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('role', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Replies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('creator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hydra_learning_management_system.users')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hydra_learning_management_system.posts')),
            ],
        ),
        migrations.AddField(
            model_name='posts',
            name='creatorid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hydra_learning_management_system.users'),
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('mid', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.TextField()),
                ('filepath', models.TextField()),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hydra_learning_management_system.courses')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hydra_learning_management_system.courses')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hydra_learning_management_system.users')),
            ],
        ),
        migrations.AddField(
            model_name='courses',
            name='creatorid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hydra_learning_management_system.users'),
        ),
        migrations.CreateModel(
            name='Assignments',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('ddl', models.DateTimeField()),
                ('url', models.TextField()),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hydra_learning_management_system.courses')),
            ],
        ),
        migrations.CreateModel(
            name='Assessments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.TextField()),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hydra_learning_management_system.courses')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hydra_learning_management_system.users')),
            ],
        ),
    ]
