# Generated by Django 4.1.7 on 2023-04-08 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hydra_learning_management_system', '0003_users_birthday_users_firstname_users_gender_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='perferredlanguage',
            new_name='preferredlanguage',
        ),
    ]
