# Generated by Django 4.1.7 on 2023-04-11 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hydra_learning_management_system', '0005_alter_courses_coursename'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizzes',
            name='cid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='hydra_learning_management_system.courses'),
        ),
    ]
