# Generated by Django 4.1.7 on 2023-04-13 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydra_learning_management_system', '0006_quizzes_cid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='enrolllist',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='posts',
            name='privacy',
            field=models.BooleanField(),
        ),
    ]
