# Generated by Django 4.1.7 on 2023-04-13 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hydra_learning_management_system', '0007_alter_courses_enrolllist_alter_posts_privacy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='enrolllist',
        ),
    ]
