# Generated by Django 4.1.7 on 2023-04-14 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydra_learning_management_system', '0008_remove_courses_enrolllist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessments',
            name='grade',
            field=models.TextField(default="{'quiz': {'quiz1': 0, 'quiz2': 0, 'quiz3': 0}, 'ass': {'ass1': 0, 'ass2': 0, 'ass3': 0}, 'final': {'final exam': 0}}"),
        ),
    ]
