# Generated by Django 4.1.7 on 2023-04-14 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydra_learning_management_system', '0009_alter_assessments_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessments',
            name='worklink',
            field=models.TextField(default='{}'),
        ),
    ]
