# Generated by Django 4.1.7 on 2023-04-14 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydra_learning_management_system', '0010_assessments_worklink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessments',
            name='grade',
            field=models.TextField(default="{'quiz': {}, 'ass': {}, 'final exam': 0}"),
        ),
    ]
