# Generated by Django 4.1.7 on 2023-04-17 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydra_learning_management_system', '0012_alter_posts_multimedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessments',
            name='grade',
            field=models.TextField(default='{"quiz": {}, "ass": {}, "final exam": 0}'),
        ),
    ]
