# Generated by Django 4.1.7 on 2023-04-19 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydra_learning_management_system', '0014_alter_assessments_grade_livestream'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestream',
            name='createtime',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='users',
            name='avatar',
            field=models.TextField(default=''),
        ),
    ]
