# Generated by Django 4.1.7 on 2023-04-19 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hydra_learning_management_system', '0015_livestream_createtime_users_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizzes',
            name='ddl',
        ),
    ]
