# Generated by Django 4.1.7 on 2023-04-19 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydra_learning_management_system', '0016_remove_quizzes_ddl'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizzes',
            name='ddl',
            field=models.TextField(default=''),
        ),
    ]
