# Generated by Django 4.1.7 on 2023-04-19 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydra_learning_management_system', '0017_quizzes_ddl'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='zoomlink',
            field=models.TextField(default=''),
        ),
    ]
