# Generated by Django 4.1.7 on 2023-04-21 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydra_learning_management_system', '0018_users_zoomlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizzes',
            name='q1',
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='quizzes',
            name='q2',
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='quizzes',
            name='q3',
            field=models.JSONField(default={}),
        ),
    ]
